server:
  port: 8089

spring:
  application:
    name: analytics-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/nexfuel

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
